DROP DATABASE SysAuth;
CREATE DATABASE IF NOT EXISTS SysAuth;
USE SysAuth;

CREATE TABLE Employees (
    EmployeeID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Role ENUM ('USER', 'ADMIN') NOT NULL,
    PRIMARY KEY (EmployeeID)
);

CREATE TABLE Credentials (
    ID INT UNSIGNED NOT NULL PRIMARY KEY,
    Password VARBINARY(255) NOT NULL,
    Email VARBINARY(255) NOT NULL UNIQUE,
    FOREIGN KEY (ID) REFERENCES Employees(EmployeeID) ON DELETE CASCADE
);

CREATE TABLE AccessLogs (
    LogID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ID INT UNSIGNED NOT NULL,
    AccessTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LogID),
    FOREIGN KEY (ID) REFERENCES Employees(EmployeeID) ON DELETE CASCADE
);