services:

  mysql:
    image: mysql:8.4
    container_name: sistema-academico-db
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: sistema-academico-phpmyadmin
    restart: unless-stopped

    ports:
      - "8080:80"

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    depends_on:
      - mysql

volumes:
  mysql_data: